# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f739c8a6f7bc9dc6fe0876e6543e90bad6ce1785c8d196460995188cfe53445ec117d72988dfd6227c33d07cdb2e256b21c44bc19e046d2ceeb2c920508c56af

test:
  secret_key_base: 91c459f5e1489015d3e00ac545cfcd73371f2619879a4e414a00d9a4029e22e46024682098c5618e695bf24f909e92dabb30d31a0ba645bc24e83cae5a67346d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
